import type { GameItem } from '@rithy-room/shared';

export const GAMES_CATALOG: GameItem[] = [
  // ==================== WEB GAMES ====================
  {
    id: 'smash-karts',
    name: 'Smash Karts',
    description: 'Multiplayer kart battle arena with power-ups and weapons',
    thumbnail: '/images/games/web/smash-karts.jpg',
    url: 'https://smashkarts.io',
    maxPlayers: '8',
    category: 'racing',
    tags: ['action', 'karts', 'multiplayer', 'popular'],
  },
  {
    id: 'bloxd-io',
    name: 'Bloxd.io',
    description: 'Minecraft-like multiplayer building and survival game',
    thumbnail: '/images/games/web/bloxd-io.jpg',
    url: 'https://bloxd.io',
    maxPlayers: '20',
    category: 'io',
    tags: ['building', 'survival', 'minecraft', 'popular'],
  },
  {
    id: 'shell-shockers',
    name: 'Shell Shockers',
    description: 'First-person shooter where everyone is an egg',
    thumbnail: '/images/games/web/shell-shockers.jpg',
    url: 'https://shellshock.io',
    maxPlayers: '8',
    category: 'action',
    tags: ['fps', 'shooter', 'eggs', 'popular'],
  },
  {
    id: 'krunker',
    name: 'Krunker.io',
    description: 'Fast-paced pixelated first-person shooter',
    thumbnail: '/images/games/web/krunker.jpg',
    url: 'https://krunker.io',
    maxPlayers: '10',
    category: 'action',
    tags: ['fps', 'shooter', 'fast-paced', 'popular'],
  },
  {
    id: 'agar-io',
    name: 'Agar.io',
    description: 'Classic cell-eating multiplayer game',
    thumbnail: '/images/games/web/agar-io.jpg',
    url: 'https://agar.io',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'classic', 'cells'],
  },
  {
    id: 'slither-io',
    name: 'Slither.io',
    description: 'Snake-like multiplayer game - grow longer and survive',
    thumbnail: '/images/games/web/slither-io.jpg',
    url: 'https://slither.io',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['snake', 'casual', 'classic'],
  },
  {
    id: '1v1-lol',
    name: '1v1.LOL',
    description: 'Build and shoot battle royale style combat',
    thumbnail: '/images/games/web/1v1-lol.jpg',
    url: 'https://1v1.lol',
    maxPlayers: '2',
    category: 'action',
    tags: ['building', 'shooter', 'battle-royale'],
  },
  {
    id: 'paper-io-2',
    name: 'Paper.io 2',
    description: 'Claim territory by drawing shapes - dont get cut!',
    thumbnail: '/images/games/web/paper-io-2.jpg',
    url: 'https://paper-io.com',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'territory', 'strategy'],
  },
  {
    id: 'basketball-stars',
    name: 'Basketball Stars',
    description: '1v1 basketball with tricks and moves',
    thumbnail: '/images/games/web/basketball-stars.jpg',
    url: 'https://www.crazygames.com/game/basketball-stars',
    maxPlayers: '2',
    category: 'sports',
    tags: ['basketball', 'sports', '1v1'],
  },
  {
    id: 'narrow-one',
    name: 'Narrow One',
    description: 'Medieval castle siege with bows and arrows',
    thumbnail: '/images/games/web/narrow-one.jpg',
    url: 'https://www.crazygames.com/game/narrow-one',
    maxPlayers: '8',
    category: 'action',
    tags: ['medieval', 'archery', 'team', 'popular'],
  },
  {
    id: 'hole-io',
    name: 'Hole.io',
    description: 'Control a black hole and swallow everything',
    thumbnail: '/images/games/web/hole-io.jpg',
    url: 'https://hole-io.com',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'destruction', 'fun'],
  },
  {
    id: 'zombs-royale',
    name: 'ZombsRoyale.io',
    description: '2D battle royale with 100 players',
    thumbnail: '/images/games/web/zombs-royale.jpg',
    url: 'https://zombsroyale.io',
    maxPlayers: '100',
    category: 'action',
    tags: ['battle-royale', 'shooter', '2d'],
  },

  // ==================== PS1 GAMES ====================
  {
    id: 'crash-bandicoot',
    name: 'Crash Bandicoot',
    description: 'Classic platform adventure with Crash',
    thumbnail: '/images/games/ps1/crash-bandicoot.jpg',
    url: 'https://www.retrogames.cc/psx-games/crash-bandicoot.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'crash', 'playstation', 'popular'],
  },
  {
    id: 'spyro-dragon',
    name: 'Spyro the Dragon',
    description: '3D platformer adventure with the purple dragon',
    thumbnail: '/images/games/ps1/spyro-the-dragon.jpg',
    url: 'https://www.retrogames.cc/psx-games/spyro-the-dragon.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'spyro', 'playstation', 'popular'],
  },
  {
    id: 'tekken-3',
    name: 'Tekken 3',
    description: 'Legendary fighting game',
    thumbnail: '/images/games/ps1/tekken-3.jpg',
    url: 'https://www.retrogames.cc/psx-games/tekken-3.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['fighting', 'arcade', 'popular'],
  },
  {
    id: 'final-fantasy-7',
    name: 'Final Fantasy VII',
    description: 'Epic RPG - Follow Cloud and AVALANCHE',
    thumbnail: '/images/games/ps1/final-fantasy-7.jpg',
    url: 'https://www.retrogames.cc/psx-games/final-fantasy-vii-usa-disc-1.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['rpg', 'jrpg', 'squaresoft', 'popular'],
  },
  {
    id: 'metal-gear-solid',
    name: 'Metal Gear Solid',
    description: 'Stealth action - Solid Snake infiltrates',
    thumbnail: '/images/games/ps1/metal-gear-solid.jpg',
    url: 'https://www.retrogames.cc/psx-games/metal-gear-solid-disc-1.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['stealth', 'action', 'konami', 'popular'],
  },
  {
    id: 'resident-evil',
    name: 'Resident Evil',
    description: 'Survival horror classic - Escape the mansion',
    thumbnail: '/images/games/ps1/resident-evil.jpg',
    url: 'https://www.retrogames.cc/psx-games/resident-evil.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['horror', 'survival', 'capcom'],
  },
  {
    id: 'gran-turismo',
    name: 'Gran Turismo',
    description: 'The real driving simulator',
    thumbnail: '/images/games/ps1/gran-turismo.jpg',
    url: 'https://www.retrogames.cc/psx-games/gran-turismo.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['racing', 'simulator', 'cars'],
  },
  {
    id: 'tony-hawk-2',
    name: "Tony Hawk's Pro Skater 2",
    description: 'Skateboarding classic - nail those combos',
    thumbnail: '/images/games/ps1/tony-hawk-2.jpg',
    url: 'https://www.retrogames.cc/psx-games/tony-hawks-pro-skater-2.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['sports', 'skateboard', 'popular'],
  },
  {
    id: 'castlevania-sotn',
    name: 'Castlevania: SOTN',
    description: 'Symphony of the Night - Explore Draculas castle',
    thumbnail: '/images/games/ps1/castlevania-sotn.jpg',
    url: 'https://www.retrogames.cc/psx-games/castlevania-symphony-of-the-night.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['action', 'metroidvania', 'konami', 'popular'],
  },
  {
    id: 'crash-team-racing',
    name: 'Crash Team Racing',
    description: 'Kart racing with Crash characters',
    thumbnail: '/images/games/ps1/crash-team-racing.jpg',
    url: 'https://www.retrogames.cc/psx-games/crash-team-racing.html',
    maxPlayers: '4',
    category: 'ps1',
    tags: ['racing', 'crash', 'multiplayer'],
  },
  {
    id: 'crash-bandicoot-2',
    name: 'Crash Bandicoot 2',
    description: 'Cortex Strikes Back - more platforming fun',
    thumbnail: '/images/games/ps1/crash-bandicoot-2.jpg',
    url: 'https://www.retrogames.cc/psx-games/crash-bandicoot-2-cortex-strikes-back.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'crash', 'popular'],
  },
  {
    id: 'crash-bandicoot-3',
    name: 'Crash Bandicoot 3: Warped',
    description: 'Time-traveling platformer adventure',
    thumbnail: '/images/games/ps1/crash-bandicoot-3.jpg',
    url: 'https://www.retrogames.cc/psx-games/crash-bandicoot-warped.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'crash', 'popular'],
  },
  {
    id: 'spyro-2',
    name: 'Spyro 2: Riptos Rage',
    description: 'Dragon adventure continues',
    thumbnail: '/images/games/ps1/spyro-2.jpg',
    url: 'https://www.retrogames.cc/psx-games/spyro-2-riptos-rage.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'spyro', 'popular'],
  },
  {
    id: 'resident-evil-2',
    name: 'Resident Evil 2',
    description: 'Survival horror in Raccoon City',
    thumbnail: '/images/games/ps1/resident-evil-2.jpg',
    url: 'https://www.retrogames.cc/psx-games/resident-evil-2-dual-shock-ver-disc-1-leon.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['horror', 'survival', 'capcom', 'popular'],
  },
  {
    id: 'twisted-metal-2',
    name: 'Twisted Metal 2',
    description: 'Vehicular combat destruction',
    thumbnail: '/images/games/ps1/twisted-metal-2.jpg',
    url: 'https://www.retrogames.cc/psx-games/twisted-metal-2.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['action', 'vehicles', 'multiplayer'],
  },
  {
    id: 'ape-escape',
    name: 'Ape Escape',
    description: 'Catch monkeys with gadgets',
    thumbnail: '/images/games/ps1/ape-escape.jpg',
    url: 'https://www.retrogames.cc/psx-games/ape-escape.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'action', 'sony'],
  },
  {
    id: 'medievil',
    name: 'MediEvil',
    description: 'Undead knight adventure',
    thumbnail: '/images/games/ps1/medievil.jpg',
    url: 'https://www.retrogames.cc/psx-games/medievil.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['action', 'adventure', 'horror'],
  },
  {
    id: 'silent-hill',
    name: 'Silent Hill',
    description: 'Psychological horror classic',
    thumbnail: '/images/games/ps1/silent-hill.jpg',
    url: 'https://www.retrogames.cc/psx-games/silent-hill.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['horror', 'survival', 'konami', 'popular'],
  },
  {
    id: 'tomb-raider',
    name: 'Tomb Raider',
    description: 'Lara Croft adventure begins',
    thumbnail: '/images/games/ps1/tomb-raider.jpg',
    url: 'https://www.retrogames.cc/psx-games/tomb-raider.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['action', 'adventure', 'popular'],
  },
  {
    id: 'wipeout-xl',
    name: 'Wipeout XL',
    description: 'Futuristic anti-gravity racing',
    thumbnail: '/images/games/ps1/wipeout-xl.jpg',
    url: 'https://www.retrogames.cc/psx-games/wipeout-xl-usa.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['racing', 'futuristic', 'fast'],
  },
  {
    id: 'parappa-rapper',
    name: 'PaRappa the Rapper',
    description: 'Kick punch its all in the mind',
    thumbnail: '/images/games/ps1/parappa-rapper.jpg',
    url: 'https://www.retrogames.cc/psx-games/parappa-the-rapper.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['rhythm', 'music', 'unique'],
  },
  {
    id: 'syphon-filter',
    name: 'Syphon Filter',
    description: 'Third-person stealth action',
    thumbnail: '/images/games/ps1/syphon-filter.jpg',
    url: 'https://www.retrogames.cc/psx-games/syphon-filter.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['action', 'stealth', 'shooter'],
  },
  {
    id: 'dino-crisis',
    name: 'Dino Crisis',
    description: 'Resident Evil with dinosaurs',
    thumbnail: '/images/games/ps1/dino-crisis.jpg',
    url: 'https://www.retrogames.cc/psx-games/dino-crisis.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['horror', 'survival', 'capcom'],
  },
  {
    id: 'vagrant-story',
    name: 'Vagrant Story',
    description: 'Dark action RPG',
    thumbnail: '/images/games/ps1/vagrant-story.jpg',
    url: 'https://www.retrogames.cc/psx-games/vagrant-story.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['rpg', 'action', 'squaresoft'],
  },

];

export const GAME_CATEGORIES = [
  { id: 'all', name: 'All Games' },
  { id: 'action', name: 'Action' },
  { id: 'racing', name: 'Racing' },
  { id: 'io', name: 'IO Games' },
  { id: 'sports', name: 'Sports' },
  { id: 'puzzle', name: 'Puzzle' },
  { id: 'ps1', name: 'PlayStation' },
] as const;

export type GameCategory = (typeof GAME_CATEGORIES)[number]['id'];

export function filterGames(
  games: GameItem[],
  category: GameCategory,
  searchQuery: string
): GameItem[] {
  return games.filter((game) => {
    const matchesCategory = category === 'all' || game.category === category;
    const matchesSearch =
      !searchQuery ||
      game.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      game.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      game.tags.some((tag) => tag.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesCategory && matchesSearch;
  });
}
