import type { GameItem } from '@rithy-room/shared';

// Helper to generate placeholder images for games
const placeholder = (name: string, color = '2563eb') =>
  `https://placehold.co/400x225/${color}/ffffff?text=${encodeURIComponent(name)}`;

export const GAMES_CATALOG: GameItem[] = [
  // ==================== WEB GAMES ====================
  {
    id: 'smash-karts',
    name: 'Smash Karts',
    description: 'Multiplayer kart battle arena with power-ups and weapons',
    thumbnail: 'https://www.crazygames.com/game/smash-karts/cover',
    url: 'https://smashkarts.io',
    maxPlayers: '8',
    category: 'racing',
    tags: ['action', 'karts', 'multiplayer', 'popular'],
  },
  {
    id: 'bloxd-io',
    name: 'Bloxd.io',
    description: 'Minecraft-like multiplayer building and survival game',
    thumbnail: 'https://bloxd.io/bloxd.png',
    url: 'https://bloxd.io',
    maxPlayers: '20',
    category: 'io',
    tags: ['building', 'survival', 'minecraft', 'popular'],
  },
  {
    id: 'shell-shockers',
    name: 'Shell Shockers',
    description: 'First-person shooter where everyone is an egg',
    thumbnail: 'https://shellshock.io/img/logo.png',
    url: 'https://shellshock.io',
    maxPlayers: '8',
    category: 'action',
    tags: ['fps', 'shooter', 'eggs', 'popular'],
  },
  {
    id: 'krunker',
    name: 'Krunker.io',
    description: 'Fast-paced pixelated first-person shooter',
    thumbnail: 'https://krunker.io/img/krunker_logo_0.png',
    url: 'https://krunker.io',
    maxPlayers: '10',
    category: 'action',
    tags: ['fps', 'shooter', 'fast-paced', 'popular'],
  },
  {
    id: 'agar-io',
    name: 'Agar.io',
    description: 'Classic cell-eating multiplayer game',
    thumbnail: 'https://agar.io/img/agar-fb.jpg',
    url: 'https://agar.io',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'classic', 'cells'],
  },
  {
    id: 'slither-io',
    name: 'Slither.io',
    description: 'Snake-like multiplayer game - grow longer and survive',
    thumbnail: 'https://slither.io/s/favicon-196x196.png',
    url: 'https://slither.io',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['snake', 'casual', 'classic'],
  },
  {
    id: '1v1-lol',
    name: '1v1.LOL',
    description: 'Build and shoot battle royale style combat',
    thumbnail: 'https://1v1.lol/images/og.jpg',
    url: 'https://1v1.lol',
    maxPlayers: '2',
    category: 'action',
    tags: ['building', 'shooter', 'battle-royale'],
  },
  {
    id: 'paper-io-2',
    name: 'Paper.io 2',
    description: 'Claim territory by drawing shapes - dont get cut!',
    thumbnail: 'https://paper-io.com/img/og-image.png',
    url: 'https://paper-io.com',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'territory', 'strategy'],
  },
  {
    id: 'basketball-stars',
    name: 'Basketball Stars',
    description: '1v1 basketball with tricks and moves',
    thumbnail: placeholder('Basketball Stars', '7c3aed'),
    url: 'https://www.crazygames.com/game/basketball-stars',
    maxPlayers: '2',
    category: 'sports',
    tags: ['basketball', 'sports', '1v1'],
  },
  {
    id: 'narrow-one',
    name: 'Narrow One',
    description: 'Medieval castle siege with bows and arrows',
    thumbnail: placeholder('Narrow One', '059669'),
    url: 'https://www.crazygames.com/game/narrow-one',
    maxPlayers: '8',
    category: 'action',
    tags: ['medieval', 'archery', 'team', 'popular'],
  },
  {
    id: 'hole-io',
    name: 'Hole.io',
    description: 'Control a black hole and swallow everything',
    thumbnail: 'https://hole-io.com/images/og.png',
    url: 'https://hole-io.com',
    maxPlayers: 'Unlimited',
    category: 'io',
    tags: ['casual', 'destruction', 'fun'],
  },
  {
    id: 'zombs-royale',
    name: 'ZombsRoyale.io',
    description: '2D battle royale with 100 players',
    thumbnail: 'https://zombsroyale.io/images/og.png',
    url: 'https://zombsroyale.io',
    maxPlayers: '100',
    category: 'action',
    tags: ['battle-royale', 'shooter', '2d'],
  },

  // ==================== N64 GAMES ====================
  {
    id: 'super-mario-64',
    name: 'Super Mario 64',
    description: 'Classic 3D platformer - collect stars in Princess Peach Castle',
    thumbnail: placeholder('Super Mario 64', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/40466-super-mario-64-usa.html',
    maxPlayers: '1',
    category: 'n64',
    tags: ['platformer', 'mario', 'nintendo', 'popular'],
  },
  {
    id: 'zelda-ocarina',
    name: 'Zelda: Ocarina of Time',
    description: 'Epic action-adventure through Hyrule',
    thumbnail: placeholder('Zelda OOT', '059669'),
    url: 'https://www.retrogames.cc/embed/40450-legend-of-zelda-the-ocarina-of-time-usa.html',
    maxPlayers: '1',
    category: 'n64',
    tags: ['adventure', 'zelda', 'nintendo', 'popular'],
  },
  {
    id: 'mario-kart-64',
    name: 'Mario Kart 64',
    description: 'Classic multiplayer kart racing',
    thumbnail: placeholder('Mario Kart 64', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/40460-mario-kart-64-usa.html',
    maxPlayers: '4',
    category: 'n64',
    tags: ['racing', 'mario', 'multiplayer', 'popular'],
  },
  {
    id: 'goldeneye-007',
    name: 'GoldenEye 007',
    description: 'Legendary FPS based on James Bond',
    thumbnail: placeholder('GoldenEye 007', '1f2937'),
    url: 'https://www.retrogames.cc/embed/40455-goldeneye-007-usa.html',
    maxPlayers: '4',
    category: 'n64',
    tags: ['fps', 'shooter', 'james-bond', 'popular'],
  },
  {
    id: 'super-smash-bros-64',
    name: 'Super Smash Bros',
    description: 'Nintendo characters battle it out',
    thumbnail: placeholder('Super Smash Bros', 'ea580c'),
    url: 'https://www.retrogames.cc/embed/40468-super-smash-bros-usa.html',
    maxPlayers: '4',
    category: 'n64',
    tags: ['fighting', 'nintendo', 'multiplayer', 'popular'],
  },
  {
    id: 'banjo-kazooie',
    name: 'Banjo-Kazooie',
    description: 'Collect jiggies in this platformer adventure',
    thumbnail: placeholder('Banjo-Kazooie', 'ca8a04'),
    url: 'https://www.retrogames.cc/embed/40453-banjo-kazooie-usa.html',
    maxPlayers: '1',
    category: 'n64',
    tags: ['platformer', 'rare', 'adventure'],
  },
  {
    id: 'starfox-64',
    name: 'Star Fox 64',
    description: 'Space shooter - Do a barrel roll!',
    thumbnail: placeholder('Star Fox 64', '1d4ed8'),
    url: 'https://www.retrogames.cc/embed/40467-star-fox-64-usa.html',
    maxPlayers: '4',
    category: 'n64',
    tags: ['shooter', 'space', 'nintendo'],
  },
  {
    id: 'pokemon-stadium',
    name: 'Pokemon Stadium',
    description: '3D Pokemon battles',
    thumbnail: placeholder('Pokemon Stadium', 'f59e0b'),
    url: 'https://www.retrogames.cc/embed/40463-pokemon-stadium-usa-europe.html',
    maxPlayers: '2',
    category: 'n64',
    tags: ['pokemon', 'nintendo', 'battle'],
  },
  {
    id: 'donkey-kong-64',
    name: 'Donkey Kong 64',
    description: '3D platformer with the Kong family',
    thumbnail: placeholder('Donkey Kong 64', '92400e'),
    url: 'https://www.retrogames.cc/embed/40454-donkey-kong-64-usa.html',
    maxPlayers: '4',
    category: 'n64',
    tags: ['platformer', 'rare', 'nintendo'],
  },
  {
    id: 'paper-mario-64',
    name: 'Paper Mario',
    description: 'RPG adventure with paper-style graphics',
    thumbnail: placeholder('Paper Mario', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/40462-paper-mario-usa.html',
    maxPlayers: '1',
    category: 'n64',
    tags: ['rpg', 'mario', 'nintendo'],
  },

  // ==================== PS1 GAMES ====================
  {
    id: 'crash-bandicoot',
    name: 'Crash Bandicoot',
    description: 'Classic platform adventure with Crash',
    thumbnail: placeholder('Crash Bandicoot', 'ea580c'),
    url: 'https://www.retrogames.cc/embed/28839-crash-bandicoot-usa.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'crash', 'playstation', 'popular'],
  },
  {
    id: 'spyro-dragon',
    name: 'Spyro the Dragon',
    description: '3D platformer adventure with the purple dragon',
    thumbnail: placeholder('Spyro', '7c3aed'),
    url: 'https://www.retrogames.cc/embed/29006-spyro-the-dragon-usa.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['platformer', 'spyro', 'playstation', 'popular'],
  },
  {
    id: 'tekken-3',
    name: 'Tekken 3',
    description: 'Legendary fighting game',
    thumbnail: placeholder('Tekken 3', '1f2937'),
    url: 'https://www.retrogames.cc/embed/29010-tekken-3-usa.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['fighting', 'arcade', 'popular'],
  },
  {
    id: 'final-fantasy-7',
    name: 'Final Fantasy VII',
    description: 'Epic RPG - Follow Cloud and AVALANCHE',
    thumbnail: placeholder('Final Fantasy VII', '1d4ed8'),
    url: 'https://www.retrogames.cc/embed/28860-final-fantasy-vii-usa-disc-1.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['rpg', 'jrpg', 'squaresoft', 'popular'],
  },
  {
    id: 'metal-gear-solid',
    name: 'Metal Gear Solid',
    description: 'Stealth action - Solid Snake infiltrates',
    thumbnail: placeholder('Metal Gear Solid', '374151'),
    url: 'https://www.retrogames.cc/embed/28916-metal-gear-solid-usa-disc-1.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['stealth', 'action', 'konami', 'popular'],
  },
  {
    id: 'resident-evil',
    name: 'Resident Evil',
    description: 'Survival horror classic - Escape the mansion',
    thumbnail: placeholder('Resident Evil', '450a0a'),
    url: 'https://www.retrogames.cc/embed/28963-resident-evil-usa.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['horror', 'survival', 'capcom'],
  },
  {
    id: 'gran-turismo',
    name: 'Gran Turismo',
    description: 'The real driving simulator',
    thumbnail: placeholder('Gran Turismo', '2563eb'),
    url: 'https://www.retrogames.cc/embed/28877-gran-turismo-usa.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['racing', 'simulator', 'cars'],
  },
  {
    id: 'tony-hawk-2',
    name: "Tony Hawk's Pro Skater 2",
    description: 'Skateboarding classic - nail those combos',
    thumbnail: placeholder('Tony Hawk 2', '65a30d'),
    url: 'https://www.retrogames.cc/embed/29014-tony-hawks-pro-skater-2-usa.html',
    maxPlayers: '2',
    category: 'ps1',
    tags: ['sports', 'skateboard', 'popular'],
  },
  {
    id: 'castlevania-sotn',
    name: 'Castlevania: SOTN',
    description: 'Symphony of the Night - Explore Draculas castle',
    thumbnail: placeholder('Castlevania SOTN', '581c87'),
    url: 'https://www.retrogames.cc/embed/28838-castlevania-symphony-of-the-night-usa.html',
    maxPlayers: '1',
    category: 'ps1',
    tags: ['action', 'metroidvania', 'konami', 'popular'],
  },
  {
    id: 'crash-team-racing',
    name: 'Crash Team Racing',
    description: 'Kart racing with Crash characters',
    thumbnail: placeholder('Crash Team Racing', 'ea580c'),
    url: 'https://www.retrogames.cc/embed/28842-crash-team-racing-usa.html',
    maxPlayers: '4',
    category: 'ps1',
    tags: ['racing', 'crash', 'multiplayer'],
  },

  // ==================== GBA GAMES ====================
  {
    id: 'pokemon-emerald',
    name: 'Pokemon Emerald',
    description: 'Pokemon adventure in the Hoenn region',
    thumbnail: placeholder('Pokemon Emerald', '059669'),
    url: 'https://www.retrogames.cc/embed/8556-pokemon-emerald-version-usa-europe.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['rpg', 'pokemon', 'nintendo', 'popular'],
  },
  {
    id: 'pokemon-firered',
    name: 'Pokemon Fire Red',
    description: 'Classic Kanto adventure remade',
    thumbnail: placeholder('Pokemon FireRed', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/8557-pokemon-fire-red-version-usa-europe.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['rpg', 'pokemon', 'nintendo', 'popular'],
  },
  {
    id: 'zelda-minish-cap',
    name: 'Zelda: Minish Cap',
    description: 'Shrink down and explore a tiny world',
    thumbnail: placeholder('Zelda Minish Cap', '059669'),
    url: 'https://www.retrogames.cc/embed/8619-legend-of-zelda-the-the-minish-cap-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['adventure', 'zelda', 'nintendo', 'popular'],
  },
  {
    id: 'mario-kart-super-circuit',
    name: 'Mario Kart: Super Circuit',
    description: 'GBA kart racing fun',
    thumbnail: placeholder('Mario Kart SC', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/8637-mario-kart-super-circuit-usa.html',
    maxPlayers: '4',
    category: 'gba',
    tags: ['racing', 'mario', 'nintendo'],
  },
  {
    id: 'super-mario-advance-4',
    name: 'Super Mario Advance 4',
    description: 'Super Mario Bros 3 remake',
    thumbnail: placeholder('SMA4: SMB3', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/8669-super-mario-advance-4-super-mario-bros-3-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['platformer', 'mario', 'nintendo'],
  },
  {
    id: 'metroid-fusion',
    name: 'Metroid Fusion',
    description: 'Samus faces the X parasites',
    thumbnail: placeholder('Metroid Fusion', '7c3aed'),
    url: 'https://www.retrogames.cc/embed/8644-metroid-fusion-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['action', 'metroidvania', 'nintendo'],
  },
  {
    id: 'fire-emblem-gba',
    name: 'Fire Emblem',
    description: 'Tactical RPG - Lead your army',
    thumbnail: placeholder('Fire Emblem', '1d4ed8'),
    url: 'https://www.retrogames.cc/embed/8504-fire-emblem-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['rpg', 'strategy', 'nintendo', 'popular'],
  },
  {
    id: 'kirby-amazing-mirror',
    name: 'Kirby & The Amazing Mirror',
    description: 'Explore a labyrinthine world',
    thumbnail: placeholder('Kirby Mirror', 'ec4899'),
    url: 'https://www.retrogames.cc/embed/8601-kirby-and-the-amazing-mirror-usa.html',
    maxPlayers: '4',
    category: 'gba',
    tags: ['platformer', 'kirby', 'nintendo'],
  },
  {
    id: 'sonic-advance',
    name: 'Sonic Advance',
    description: 'Fast-paced platforming with Sonic',
    thumbnail: placeholder('Sonic Advance', '2563eb'),
    url: 'https://www.retrogames.cc/embed/8664-sonic-advance-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['platformer', 'sonic', 'sega'],
  },
  {
    id: 'golden-sun',
    name: 'Golden Sun',
    description: 'Epic RPG adventure with Psynergy',
    thumbnail: placeholder('Golden Sun', 'f59e0b'),
    url: 'https://www.retrogames.cc/embed/8524-golden-sun-usa.html',
    maxPlayers: '1',
    category: 'gba',
    tags: ['rpg', 'jrpg', 'nintendo', 'popular'],
  },

  // ==================== NES GAMES ====================
  {
    id: 'super-mario-bros',
    name: 'Super Mario Bros',
    description: 'The classic platformer that started it all',
    thumbnail: placeholder('Super Mario Bros', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/36227-super-mario-bros-usa-europe.html',
    maxPlayers: '2',
    category: 'nes',
    tags: ['platformer', 'mario', 'nintendo', 'popular'],
  },
  {
    id: 'zelda-nes',
    name: 'The Legend of Zelda',
    description: 'Original adventure in Hyrule',
    thumbnail: placeholder('Zelda NES', '059669'),
    url: 'https://www.retrogames.cc/embed/36154-legend-of-zelda-the-usa.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['adventure', 'zelda', 'nintendo', 'popular'],
  },
  {
    id: 'contra-nes',
    name: 'Contra',
    description: 'Run and gun action - Up Up Down Down',
    thumbnail: placeholder('Contra', '1f2937'),
    url: 'https://www.retrogames.cc/embed/36055-contra-usa.html',
    maxPlayers: '2',
    category: 'nes',
    tags: ['action', 'shooter', 'konami', 'popular'],
  },
  {
    id: 'mega-man-2',
    name: 'Mega Man 2',
    description: 'Defeat the Robot Masters',
    thumbnail: placeholder('Mega Man 2', '2563eb'),
    url: 'https://www.retrogames.cc/embed/36174-mega-man-2-usa.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['action', 'platformer', 'capcom', 'popular'],
  },
  {
    id: 'metroid-nes',
    name: 'Metroid',
    description: 'Explore planet Zebes as Samus',
    thumbnail: placeholder('Metroid', '7c3aed'),
    url: 'https://www.retrogames.cc/embed/36178-metroid-usa.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['action', 'exploration', 'nintendo'],
  },
  {
    id: 'castlevania-nes',
    name: 'Castlevania',
    description: 'Whip your way through Draculas castle',
    thumbnail: placeholder('Castlevania', '581c87'),
    url: 'https://www.retrogames.cc/embed/36042-castlevania-usa.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['action', 'horror', 'konami'],
  },
  {
    id: 'ninja-gaiden',
    name: 'Ninja Gaiden',
    description: 'Challenging ninja action',
    thumbnail: placeholder('Ninja Gaiden', '1f2937'),
    url: 'https://www.retrogames.cc/embed/36192-ninja-gaiden-usa.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['action', 'ninja', 'tecmo'],
  },
  {
    id: 'duck-hunt',
    name: 'Duck Hunt',
    description: 'Classic shooting game',
    thumbnail: placeholder('Duck Hunt', '65a30d'),
    url: 'https://www.retrogames.cc/embed/36081-duck-hunt-usa-europe.html',
    maxPlayers: '2',
    category: 'nes',
    tags: ['shooter', 'light-gun', 'nintendo'],
  },
  {
    id: 'tetris-nes',
    name: 'Tetris',
    description: 'The legendary puzzle game',
    thumbnail: placeholder('Tetris', '0891b2'),
    url: 'https://www.retrogames.cc/embed/36246-tetris-usa.html',
    maxPlayers: '2',
    category: 'nes',
    tags: ['puzzle', 'classic', 'popular'],
  },
  {
    id: 'pac-man-nes',
    name: 'Pac-Man',
    description: 'Eat dots, avoid ghosts',
    thumbnail: placeholder('Pac-Man', 'f59e0b'),
    url: 'https://www.retrogames.cc/embed/36198-pac-man-usa-namco.html',
    maxPlayers: '1',
    category: 'nes',
    tags: ['arcade', 'classic', 'namco'],
  },

  // ==================== SNES GAMES ====================
  {
    id: 'super-mario-world',
    name: 'Super Mario World',
    description: 'Platformer masterpiece with Yoshi',
    thumbnail: placeholder('Super Mario World', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/46254-super-mario-world-usa.html',
    maxPlayers: '2',
    category: 'snes',
    tags: ['platformer', 'mario', 'nintendo', 'popular'],
  },
  {
    id: 'zelda-alttp',
    name: 'Zelda: A Link to the Past',
    description: 'Top-down adventure classic',
    thumbnail: placeholder('Zelda ALTTP', '059669'),
    url: 'https://www.retrogames.cc/embed/46176-legend-of-zelda-the-a-link-to-the-past-usa.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['adventure', 'zelda', 'nintendo', 'popular'],
  },
  {
    id: 'chrono-trigger',
    name: 'Chrono Trigger',
    description: 'Time-traveling RPG masterpiece',
    thumbnail: placeholder('Chrono Trigger', '2563eb'),
    url: 'https://www.retrogames.cc/embed/46081-chrono-trigger-usa.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['rpg', 'jrpg', 'squaresoft', 'popular'],
  },
  {
    id: 'super-metroid',
    name: 'Super Metroid',
    description: 'The defining metroidvania experience',
    thumbnail: placeholder('Super Metroid', '7c3aed'),
    url: 'https://www.retrogames.cc/embed/46250-super-metroid-usa-europe.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['action', 'metroidvania', 'nintendo', 'popular'],
  },
  {
    id: 'donkey-kong-country',
    name: 'Donkey Kong Country',
    description: 'Beautiful platformer with DK and Diddy',
    thumbnail: placeholder('DKC', '92400e'),
    url: 'https://www.retrogames.cc/embed/46089-donkey-kong-country-usa.html',
    maxPlayers: '2',
    category: 'snes',
    tags: ['platformer', 'rare', 'nintendo', 'popular'],
  },
  {
    id: 'street-fighter-2-turbo',
    name: 'Street Fighter II Turbo',
    description: 'Classic fighting game',
    thumbnail: placeholder('SF2 Turbo', 'ea580c'),
    url: 'https://www.retrogames.cc/embed/46237-street-fighter-ii-turbo-hyper-fighting-usa.html',
    maxPlayers: '2',
    category: 'snes',
    tags: ['fighting', 'capcom', 'arcade', 'popular'],
  },
  {
    id: 'final-fantasy-6',
    name: 'Final Fantasy VI',
    description: 'Epic RPG with a massive cast',
    thumbnail: placeholder('Final Fantasy VI', '1d4ed8'),
    url: 'https://www.retrogames.cc/embed/46110-final-fantasy-vi-usa.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['rpg', 'jrpg', 'squaresoft'],
  },
  {
    id: 'earthbound',
    name: 'EarthBound',
    description: 'Quirky modern-day RPG adventure',
    thumbnail: placeholder('EarthBound', 'ec4899'),
    url: 'https://www.retrogames.cc/embed/46093-earthbound-usa.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['rpg', 'nintendo', 'quirky'],
  },
  {
    id: 'super-mario-kart',
    name: 'Super Mario Kart',
    description: 'The original kart racer',
    thumbnail: placeholder('Super Mario Kart', 'dc2626'),
    url: 'https://www.retrogames.cc/embed/46252-super-mario-kart-usa.html',
    maxPlayers: '2',
    category: 'snes',
    tags: ['racing', 'mario', 'nintendo', 'popular'],
  },
  {
    id: 'mega-man-x',
    name: 'Mega Man X',
    description: 'Action-packed robot battles',
    thumbnail: placeholder('Mega Man X', '2563eb'),
    url: 'https://www.retrogames.cc/embed/46196-mega-man-x-usa.html',
    maxPlayers: '1',
    category: 'snes',
    tags: ['action', 'platformer', 'capcom'],
  },
];

export const GAME_CATEGORIES = [
  { id: 'all', name: 'All Games' },
  { id: 'action', name: 'Action' },
  { id: 'racing', name: 'Racing' },
  { id: 'io', name: 'IO Games' },
  { id: 'sports', name: 'Sports' },
  { id: 'puzzle', name: 'Puzzle' },
  { id: 'n64', name: 'Nintendo 64' },
  { id: 'ps1', name: 'PlayStation' },
  { id: 'gba', name: 'Game Boy Advance' },
  { id: 'nes', name: 'NES' },
  { id: 'snes', name: 'Super Nintendo' },
] as const;

export type GameCategory = (typeof GAME_CATEGORIES)[number]['id'];

export function filterGames(
  games: GameItem[],
  category: GameCategory,
  searchQuery: string
): GameItem[] {
  return games.filter((game) => {
    const matchesCategory = category === 'all' || game.category === category;
    const matchesSearch =
      !searchQuery ||
      game.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      game.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      game.tags.some((tag) => tag.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesCategory && matchesSearch;
  });
}
